import Head from 'next/head'
import ManualNavbar from '@/components/ManualNavbar' /* manual connect button */
import Navbar from '@/components/Navbar'
import LotteryEntrance from '@/components/LotteryEntrance'

export default function Home() {
  return (
    <>
      <Head>
        <title>Smart Contract Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Hello</h2>
      <Navbar/>
      <LotteryEntrance />
    </>
  )
}
